/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentGradeBoard2;

import javax.swing.JOptionPane;
import java.io.File;
import java.io.PrintWriter;

/**
 *
 * @author dell
 */
public class Students2 extends javax.swing.JFrame {
     String [] StuNO = new String [10000000];
    int [] M = new int [10000000];
    char grade[] = new char[10000000];
    int count = 0;
    int Total = 0 ;
    double average = 0.0;
    int max = 0;
    int min;
    
 
    /**
     * Creates new form Students2
     */
    public Students2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Result = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Marks = new javax.swing.JTextField();
        Index = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        StuRecords = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Index No");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 110, 100, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Results");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(290, 90, 100, 20);

        Result.setEditable(false);
        Result.setColumns(20);
        Result.setRows(5);
        jScrollPane2.setViewportView(Result);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(290, 120, 230, 320);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("Clear Students");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(60, 450, 120, 30);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setText("Update Results ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(220, 450, 120, 30);

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton5.setText("Save Summary");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(380, 450, 116, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Marks");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 140, 80, 30);

        Marks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarksActionPerformed(evt);
            }
        });
        jPanel2.add(Marks);
        Marks.setBounds(110, 150, 150, 20);

        Index.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IndexActionPerformed(evt);
            }
        });
        jPanel2.add(Index);
        Index.setBounds(110, 120, 150, 22);

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton4.setText("Add Student");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(150, 180, 110, 21);

        StuRecords.setEditable(false);
        StuRecords.setColumns(20);
        StuRecords.setRows(5);
        StuRecords.setAutoscrolls(false);
        jScrollPane1.setViewportView(StuRecords);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(30, 220, 230, 220);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Records");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(30, 190, 90, 30);

        jPanel1.setBackground(new java.awt.Color(107, 109, 109));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Student Information");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(252, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(0, 0, 730, 80);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IndexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IndexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IndexActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

count=0;
  Total=0;
  
  average =0.0;
  max=0;
  min=1000;        
        
        
        StuRecords.setText(null);

Result.setText(null); 
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    if(Index.getText().isEmpty()|| Marks.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"please Enter all Fields");
        }else{
            StuNO[count] = Index.getText();
            M[count] = Integer.parseInt(Marks.getText());
            count +=1;
            String existingValue = StuRecords.getText();
            StuRecords.setText(existingValue+"\n"+StuNO[count - 1]+" "+"-"+" "+M[count-1]);
           
            Index.setText(null);
            Marks.setText(null);
            
            
               
                
                
                
            
            
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 Total = 0;
        for(int p = 0; p<count ; p++){
             
        if(M[p]>=75 ){
            grade[p] = 'A';
            }else if(M[p]>=65){
                grade[p] = 'B';}
            else if (M[p]>=55){
                grade[p] = 'C';}
            else if (M[p]>=35){
                grade[p] = 'S';}
            else{
            
            grade[p] = 'W';
            
            
            }}
  
        
        
        for(int i = 0; i<count; i++){
        Total += M[i];}
        average = Total/count;
        for(int j = 0; j<count; j++){
        if (M[j]>max){
        max = M[j];
        continue;
        }
        
        
        }
        min = M[0];
        for(int k = 1; k<count; k++){
        if (M[k]<min){
            min = M[k];
            continue;
            
        }
        
        }
        
     Result.setText(null);
     Result.setText("No. of Student = "+(count+"")+"\n"+"Minimum Mark = "+ (min+"")+"\n"+"Maximum Mark = "+(max+"")+"\n"+"Average Mark = "+(average+"")+"\n");
      for(int m=0;m<count;m++){
        String existingValue2= Result.getText();
            
            Result.setText( existingValue2+"\n"+StuNO[m]+" "+"-"+"" + M[m]+" "+"("+grade[m]  +")" ); 
            
        }
      
      
        
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
      for(int i=0;i<count;i++){
            Total+=M[i];
        }
        average = Total/count;
        
        for(int j=0;j<count;j++){
           
           if(M[j]>max){
               max=M[j];
           continue;   
           }
        }
        min=M[0];
        for(int k=1;k<count;k++){
           
           if(M[k]<min){
               min=M[k];
               continue;
        }
        }
        Result.setText("No. Of Student ="+(count+"") +"\n"+"Minimum Mark ="+ (min+"")+"\n"+"Maximum Mark ="+ (max+ "")+"\n"+"Average Mark ="+ (average+"")+"\n");
  
        for(int l=0;l<count;l++){
        String existingValue1= Result.getText();
            
            Result.setText( existingValue1+"\n"+StuNO[l]+" "+"-" + M[l]+" "+"("+grade[l]  +")" ); 
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    
        try {
            File file = new File("result_summery.txt");
            if(!file.exists()){
                file.createNewFile();
            }
            PrintWriter pw = new PrintWriter(file);
            pw.print(Result.getText());
            pw.close();
            
            JOptionPane.showMessageDialog(null, "Successfully Saved ");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error !");
        
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void MarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MarksActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Students2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Students2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Students2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Students2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Students2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Index;
    private javax.swing.JTextField Marks;
    private javax.swing.JTextArea Result;
    private javax.swing.JTextArea StuRecords;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
